### PR TITLE
update blinky for nucleo-h743zi2

### PR DESCRIPTION
**Pull request by astraw**
@robamu here I update the blinky example for the nucleo-h743zi2 board. Are you using the nucleo-h743zi? I actually have a lot more of the zi2 version boards, and so I would prefer to update this repository to focus on that board. What do you think?

### CODE REVIEW

**Comment by robamu** [comment]
I can get a ZI2 variant board next week, but the board I have right now is still the ZI variant. Maybe we can use a cargo feature for that and default to ZI2?

**Comment by astraw** [comment]
OK, thanks for the info. It is useful to know you have a real ZI board. (As far as I remember and understand, ST did a sort of weird thing where they minimized emphasizing the differences between ZI2 and ZI, and released only limited quantities of the original ZI. Therefore, I guess there are relatively few ZI boards in the wild.)

Still, if we make the goal of this repository a very initial "first step" as I suggested in #7, I think we should aim to seamlessly support the subset of features that work on both ZI and ZI2. (At least when using the default cargo feature selection.)

**Comment by robamu** [comment]
Then it might be a better idea to only use the two LEDs where the pin has not changed

**Comment by astraw** [comment]
This was fixed in 29e66f53bf05911ba434ad45d70b15d79d1d816a - it turns out the two boards have different LED2 pin assignments (and colors).

**Pull request closed without merging**
