### PR TITLE
SPI example

### PR DESCRIPTION
**Pull request by robamu**
I added a simple SPI example. It uses `send` and `transfer` to send dummy strings, and it sends all received bytes to the serial port.

### CODE REVIEW

**Comment by astraw** [comment]
This is failing to build for me with `cargo build --release` at the command line:

```
   Compiling nucleo-h743zi v0.1.0 (C:\Users\drand\Documents\src\nucleo-h743zi)
error[E0432]: unresolved imports `stm32h7xx_hal::spi`, `stm32h7xx_hal::block`
  --> src\bin\spi.rs:14:40
   |
14 | use stm32h7xx_hal::{prelude::*, timer, spi, block, serial};
   |                                        ^^^  ^^^^^ no `block` in the root
   |                                        |
   |                                        no `spi` in the root

error: cannot determine resolution for the macro `block`
  --> src\bin\spi.rs:82:9
   |
82 |         block!(timer.wait()).unwrap();
   |         ^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error[E0433]: failed to resolve: could not find `config` in `serial`
  --> src\bin\spi.rs:56:17
   |
56 |         serial::config::Config::default().baudrate(115200.bps()),
   |                 ^^^^^^ could not find `config` in `serial`

error[E0599]: no method named `constrain` found for struct `PWR` in the current scope
  --> src\bin\spi.rs:22:22
   |
22 |     let pwr = dp.PWR.constrain();
   |                      ^^^^^^^^^ method not found in `PWR`

error[E0599]: no method named `use_hse` found for struct `Rcc` in the current scope
  --> src\bin\spi.rs:27:19
   |
27 |     let rcc = rcc.use_hse(8.mhz()).bypass_hse().sys_ck(400.mhz()).pll1_q_ck(100.mhz());
   |                   ^^^^^^^ method not found in `Rcc`

error[E0599]: no method named `into_alternate_af5` found for struct `PA5` in the current scope
  --> src\bin\spi.rs:34:25
   |
34 |     let sck = gpioa.pa5.into_alternate_af5();
   |                         ^^^^^^^^^^^^^^^^^^ method not found in `PA5<Input<Floating>>`

error[E0599]: no method named `into_alternate_af5` found for struct `PA6` in the current scope
  --> src\bin\spi.rs:35:26
   |
35 |     let miso = gpioa.pa6.into_alternate_af5();
   |                          ^^^^^^^^^^^^^^^^^^ method not found in `PA6<Input<Floating>>`

error[E0599]: no method named `into_alternate_af5` found for struct `PA7` in the current scope
  --> src\bin\spi.rs:36:26
   |
36 |     let mosi = gpioa.pa7.into_alternate_af5();
   |                          ^^^^^^^^^^^^^^^^^^ method not found in `PA7<Input<Floating>>`

error[E0599]: no method named `spi` found for struct `stm32h7xx_hal::stm32::SPI1` in the current scope
  --> src\bin\spi.rs:39:27
   |
39 |     let mut spi = dp.SPI1.spi(
   |                           ^^^ method not found in `stm32h7xx_hal::stm32::SPI1`

error[E0599]: no method named `into_alternate_af7` found for struct `PD8` in the current scope
  --> src\bin\spi.rs:51:15
   |
51 |     gpiod.pd8.into_alternate_af7();
   |               ^^^^^^^^^^^^^^^^^^ method not found in `PD8<Input<Floating>>`

error[E0599]: no method named `into_alternate_af7` found for struct `PD9` in the current scope
  --> src\bin\spi.rs:52:15
   |
52 |     gpiod.pd9.into_alternate_af7();
   |               ^^^^^^^^^^^^^^^^^^ method not found in `PD9<Input<Floating>>`

error[E0061]: this function takes 5 arguments but 4 arguments were supplied
   --> src\bin\spi.rs:54:18
    |
54  |     let serial = serial::Serial::usart3(
    |                  ^^^^^^^^^^^^^^^^^^^^^^ expected 5 arguments
55  |         dp.USART3,
    |         ---------
56  |         serial::config::Config::default().baudrate(115200.bps()),
    |         --------------------------------------------------------
57  |         ccdr.peripheral.USART3,
    |         ----------------------
58  |         &ccdr.clocks
    |         ------------ supplied 4 arguments
    |
note: associated function defined here
   --> C:\Users\drand\.cargo\registry\src\github.com-1ecc6299db9ec823\stm32h7xx-hal-0.1.0\src\serial.rs:237:14
    |
237 |     USART3: (usart3, APB1, usart3en, usart3rst, pclk1, lenr, lrstr),
    |              ^^^^^^

error[E0599]: no method named `unwrap` found for struct `Serial` in the current scope
  --> src\bin\spi.rs:59:7
   |
59 |     ).unwrap();
   |       ^^^^^^ method not found in `Serial<stm32h7xx_hal::stm32::USART3, (_, _)>`

error[E0061]: this function takes 4 arguments but 3 arguments were supplied
   --> src\bin\spi.rs:66:21
    |
66  |     let mut timer = timer::Timer::tim1(dp.TIM1, ccdr.peripheral.TIM1, &ccdr.clocks);
    |                     ^^^^^^^^^^^^^^^^^^ -------  --------------------  ------------ supplied 3 arguments
    |                     |
    |                     expected 4 arguments
    |
note: associated function defined here
   --> C:\Users\drand\.cargo\registry\src\github.com-1ecc6299db9ec823\stm32h7xx-hal-0.1.0\src\timer.rs:162:12
    |
162 |     TIM1: (tim1, APB2, tim1en, tim1rst, enr, rstr),
    |            ^^^^

warning: unused import: `core::fmt::Write`
  --> src\bin\spi.rs:15:5
   |
15 | use core::fmt::Write;
   |     ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

Some errors have detailed explanations: E0061, E0432, E0433, E0599.
For more information about an error, try `rustc --explain E0061`.
warning: `nucleo-h743zi` (bin "spi") generated 1 warning
error: could not compile `nucleo-h743zi` due to 14 previous errors; 1 warning emitted
```

Once this is solved, I would be happy to merge this, as I think it is a useful example. It may be useful to add a comment describing one or more specific SPI devices that could be used to test this. I did not test the SPI code myself due to the build failure and not having an SPI device.

In general, it seems like a better idea to put new examples into the https://github.com/stm32-rs/stm32h7xx-hal which is more active than this, albeit not specific to a particular board. I think it would be useful to make `stm32h7xx-hal ` easy to use for testing and debugging with a relevant Nucleo board.

**Comment by robamu** [comment]
I'm not sure the pin defintions are identical and I liked using this pin setup which is similar to the Arduino. The compile error might be related to the command building all the binaries. I'll check this

**Comment by robamu** [comment]
I have resolved the conflicts. It should build now. I might try the example in the HAL crate. The big advantage of these board specific examples is that these work out of the box for a board variant. I looked through many examples, some are more generic and should in principle work on every board, some are really board specific. I might create an issue for that

**Comment by astraw** [comment]
This works and runs for me but I haven't tested the SPI hardware signals themselves.

**Pull request merged**
